### ISSUE TITLE
Socket.io Success Callback (data-acknowledgements)

### ISSUE THREAD

**Issue by hugominas** [doquangtan/gofiber-socket.io#9]
I am looking for a way to implement data-acknowledgements https://socket.io/docs/v4/emitting-events/#acknowledgements

This is handy for frontend as you can implement it like this:

socket.emit('my custom method', {content: json},() -> console.log("Emitted"))

I am not sure if this is something you plan to include but it would be great to be able to use this

Kind Regards
Hugo

**Comment by doquangtan** [comment]
ok, i will do it in next version

**Comment by doquangtan** [comment]
I commit version v0.1.6, emit ack supported. Enjoy

**Comment by doquangtan** [comment]
I have updated the document here https://github.com/[doquangtan/gofiber-socket.io](https://github.com/doquangtan/gofiber-socket.io?tab=readme-ov-file#socketoneventname-callback)?tab=readme-ov-file#socketoneventname-callback

**Comment by hugominas** [comment]
Amazing @doquangtan going to test it out. This saves a lot of state changes on the frontend. Thanks so much for all the effort with this library.

**Comment by hugominas** [comment]
I just run a few test and it looks like the implementation is working on the server side Emit but not on the cliente side, not sure how or if this is possible to implement in golang as I am learning at the moment.

So if I implemente on cliente side

```socket.emit('my custom method', {content: json})  // this works

socket.emit('my custom method', {content: json}, (a) -> console.log("Emitted", a)) //this request fails
```

On nodejs Socket.io implementation the server looks like this
```
socket.on("setBookings", async function (data, cb) {
   cb(await getAll(user));
})
```
As you can see there are two params
```
socket.On("getInitData", func(event *socketio.EventPayload, cb *socketio.EventAck ) {
  ... do the route logic
 cb(SomeData...) // send the request callback
})
```

**Comment by hugominas** [comment]
@doquangtan Thank you for the update the implementation of the Ack looks like is should work, but my requests keep getting ignored if I add a second param. I read that this could be due to the versions of the socket.io client / server beeing different so I updated to user the 4.8.1 like in your exemples.

However when as soon as I add the Ack param to the emit the request is ignored 

```
// this works
socket.emit(callType, data); 

// this fails
  socket.emit(callType, data, (d, obj) => {
      console.log(d, obj);
      return cb && cb(obj);
 });
```

On the go server 
```
socket.On("getElements", func(event *socketio.EventPayload) {
	println("event", len(event.Data))

	data, err := event.Data[0].(map[string]interface{})
	if !err {
		println("data is not a map")
	}

	for key, value := range data {
		println("key", key, "value", value)
	}

	if event.Ack == nil {
		println("NO event.Ack")
	}

	if event.Ack != nil {
		println("event.Ack")
		event.Ack("hello", map[string]interface{}{
			"Test": "ok",
		})
	}
})
```

I have tried sending the ACK with the request param but it gets ignored because its a js function.

I have not tried running your exemple as I have everything inside docker, but if you want I can set up a dockerfile to run it localy.

Once again thanks so much for this, this is an incredible implementation that is not available on other go libraries

Kind regards
Hugo

**Comment by doquangtan** [comment]
> @doquangtan Thank you for the update the implementation of the Ack looks like is should work, but my requests keep getting ignored if I add a second param. I read that this could be due to the versions of the socket.io client / server beeing different so I updated to user the 4.8.1 like in your exemples.
> 
> However when as soon as I add the Ack param to the emit the request is ignored
> 
> ```
> // this works
> socket.emit(callType, data); 
> 
> // this fails
>   socket.emit(callType, data, (d, obj) => {
>       console.log(d, obj);
>       return cb && cb(obj);
>  });
> ```
> 
> On the go server the event.Callback is not available so after reading your readme I realized it is called Ack
> 
> ```
> socket.On("getElements", func(event *socketio.EventPayload) {
> 	println("event", len(event.Data))
> 
> 	data, err := event.Data[0].(map[string]interface{})
> 	if !err {
> 		println("data is not a map")
> 	}
> 
> 	for key, value := range data {
> 		println("key", key, "value", value)
> 	}
> 
> 	if event.Ack == nil {
> 		println("NO event.Ack")
> 	}
> 
> 	if event.Ack != nil {
> 		println("event.Ack")
> 		event.Ack("hello", map[string]interface{}{
> 			"Test": "ok",
> 		})
> 	}
> })
> ```
> 
> I have tried sending the ACK with the request param but it gets ignored because its a js function.
> 
> I have not tried running your exemple as I have everything inside docker, but if you want I can set up a dockerfile to run it localy.
> 
> Once again thanks so much for this, this is an incredible implementation that is not available on other go libraries
> 
> Kind regards Hugo

I was fixed in ver 0.1.8 try it

**Comment by hugominas** [comment]
Thanks, it was not working, so I cloned your repo, tested with your client version, but still no luck. Your version is working so it had to be an implemention problem on my end. 

I finally found that if I add specific path to the onConnection io.Of("/admin").OnConnection as oposed to io.OnConnection the Ack started working. I haven't used the .Of(path) before but it makes sense to seperate logic in the backend. 

Thank you so much for your help!

**Comment by doquangtan** [comment]
> Thanks, it was not working for me so I cloned your repo tested and tested and your version was working flawlessly, so it had to be an implemention problem on my end.
> 
> I finally found that if I add specific path to the onConnection io.Of("/admin").OnConnection as oposed to io.OnConnection the Ack started working. I haven't used the .Of(path) before but it makes sense to seperate logic in the backend.
> 
> Thank you so much for your help!

Yep, i found isuse in root name space not detech ack id. I was fixed this bug in ver 0.1.9 try again. Thank you.

**Comment by hugominas** [comment]
Just wanted to thank you for this amazing lib, it has saved me a lot of time. This is our first golang socket.io implementation comming from nodeJs its working pretty fast and super efficient.

Thank you!!

https://github.com/user-attachments/assets/e47e08d3-84ae-4304-9344-9666b3f4be77
